version: "3.9"
services:
  web:
    container_name: web3
    hostname: web
    build:
      context: ./airerp
      dockerfile: Dockerfile
    command: gunicorn airerp.wsgi:application --workers 5 --timeout=600 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres3
    hostname: postgres
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  nginx:
    container_name: nginx3
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    container_name: redis2
    hostname: "redis"
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  redis-commander:
    container_name: redis-commander2
    hostname: redis-commander2
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"


volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_volume: