version: "3.9"
services:
  web:
    container_name: web3
    hostname: web
    build:
      context: ./airerp
      dockerfile: Dockerfile

    command: daphne -b 0.0.0.0 -p 8000 airerp.asgi:application
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres

  worker-sender:
    container_name: worker-sender
    build:
      context: ./airerp
      dockerfile: ./airerp/Dockerfile
    command: celery -A airerp.celery worker --pool=solo -l INFO
    env_file:
      - .env

  postgres:
    container_name: postgres3
    hostname: postgres
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  nginx:
    container_name: nginx3
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    container_name: redis2
    hostname: "redis"
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data


volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_volume: